fixed uniqueWithin validation bugs.
Issue: https://github.com/medic/medic-projects/issues/56

This validation was failing because the lucene query was incorrectly
constructed.

- To query on integer values we need to use the <int> prefix on the
  query otherwise the query doesn't match and always returns an empty
  array.

- formatParam was failing on integer values with:

    lib/validation.js:36
    value = value.replace(/"/g, '\\"');
                  ^
    TypeError: Object 1 has no method 'replace'

- It seems the ISO date standard (the one returned by .toISOString()
  with the trailing Z that designates Zulu/GMT time) fails on Lucene.  I
  opened an upstream issue for this and left a comment in the code.

Net change looks like this:

// fails
```
patient_name:"irene" AND last_menstrual_period:"1" AND reported_date:[2015-07-27T13:14:40.564Z TO 3000-01-01T00:00:00]
```

// works
```
patient_name:"irene" AND last_menstrual_period<int>:1 AND reported_date:[2015-07-27T13:14:40.564 TO 3000-01-01T00:00:00]
```