check for doc before using it. fixes strange crash in sentinel.
not sure what caused this but the patch shouldn't hurt. sentinel was running
normally but maybe came across some inconsistency when processing
ohw_birth_report.

...
loading queue ohw_birth_report

/Users/mandric/dev/kujua/sentinel/lib/utils.coffee:20
      return (_ref = doc.related_entities) != null ? (_ref1 = _ref.clinic) !=
                        ^
TypeError: Cannot read property 'related_entities' of undefined
    at Object.getParentPhone (/Users/mandric/dev/kujua/sentinel/lib/utils.coffee:20:25)
    at /Users/mandric/dev/kujua/sentinel/transitions/ohw_birth_report.js:30:37
    at /Users/mandric/dev/kujua/sentinel/lib/utils.coffee:34:18
    at IncomingMessage.<anonymous> (/Users/mandric/dev/kujua/sentinel/node_modules/felix-couchdb/lib/couchdb.js:250:26)
    at IncomingMessage.emit (events.js:88:20)
    at HTTPParser.onMessageComplete (http.js:137:23)
    at Socket.ondata (http.js:1150:24)
    at TCP.onread (net.js:374:27)